### ISSUE TITLE
VMWare workflow validate fails

### ISSUE THREAD

**Issue by claudiol** [mikthoma/ocpag-repo#9]
The run for the VMWare bundle failed. 
/home/trustedinfras3/actions-runner/_work/_temp/caffb3d2-c36b-4159-a29b-c6743ca7502a.sh: line 2: vmware/sha256sum.txt: No such file or directory
Error: Process completed with exit code 1.

There should be a existence check in case the file does not exist.

File affected: ocpag-repo/.github/workflows/vmware.yml
Line: 67

**Comment by ckupe** [comment]
https://github.com/mikthoma/ocpag-repo/blob/main/.github/workflows/vmware.yml#L67

This was fixed with the recent change to checksum validation. Issue was the sha256sum command was hashing its own lock file, which lead to transient and inconsistent behavior.

outputting the checksum file to a temp directory then moving it to the sync folder for S3 upload solved the issue.
